import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head"; // Importar o componente Head
import Script from "next/script"; // Importar o componente Script

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-LWVS0DCKXX"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-LWVS0DCKXX');
        `}
      </Script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
